name: "Get & Cache Dependencies"
description: "Get the dependencies (via npm) and cache them"
inputs: 
  caching:
    description: 'Whether to cache dependencies or not'
    required: false
    default: 'true'
#We can put outputs to our custom actions with a used-cached identifier
#We add value to refer to one of our jobs with dynamic expression - a step context
#We need to refer to one of our steps with help of ID assigned to these steps
#We added id to a Install Dependencies step (line 31)
#We use ID from a Install Dependencies step (line 31)
#After setting the value for the overall action output
#We reach to this  install step (line 30), to the cache output (line 35) by using outputs.cache
#Thanks to that, the value from lines 27 (input value), it will be provided for this used-cache output (line 17)
outputs:
  used-cache:
    description: 'Whether the cache was used'
    value: ${{ steps.install.outputs.cache }}
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
#I set a cache output of this step to the value of the caching input
      run: |
        npm ci
        echo "cache='${{ inputs.caching }}'" >> $GITHUB_OUTPUT
      shell: bash
