name: "Get & Cache Dependencies"
description: "Get the dependencies (via npm) and cache them"
#We add these two steps as steps to this Custom Action
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
#We need to add a special key - it is a shell key where you choose which shell should be used for executing this step
#We use bash as a shell - we use shell in this step because we execute a command in a shell.
#In another steps we do not do it, because we use a uses key
      shell: bash
