name: Custom Composite Action
#We are going to create Actions that can be used only by this project
#Therefore, we create a actions/cached-deps folder and create an action.yml file to create Custom Actions
#If we want to create actions that are available to different workflows in different repositories 
#We need to create a standalone repository
#We intend to outsource the step for caching the dependencies and for installing dependencies into a separate action
#We put these steps into a cached-deps folder. An action is a part of workflows
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
#We use our own custom actions, we still use the uses key. 
#This is a local action. It is stored locally in this project.
#Therefore, we put in a value uses a path to this action folder
#We are going to use this Custom Actions in all jobs
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
        with: 
          caching: 'false'
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
#We add a Custom Action here:
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
      - name: Test code
        id: run-tests
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
#We add a Custom Action here:
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
      - name: Build website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls
      - name: Deploy site
        run: echo "Deploying..."

#In jobs, where we use a Custom Action, in a Load & cache dependencies Step 
#In a GitHub Action workflow we can see that we use a Custom Action
#We can see ./.github/actions/cached-deps <- it is a path for a Custom Action
