name: 1c. Custom Composite Action Inputs
on:
  push:
    branches:
      - main
#We want to use caching for test and build jobs, but not for a lint job
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps-input
#We add a with keyword, then we have a caching input (from cached-deps-input/actions/yml),
#Thus I add the caching key here. We set it to false 
#It should disable caching for this action in this lint job in this step here
        with: 
          caching: 'false'
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps-input
      - name: Test code
        id: run-tests
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps-input
      - name: Build website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls
      - name: Deploy site
        run: echo "Deploying..."

#In GitHub Action Workflow, in a lint job,
#We can see that it does not cache the dependencies, but it reinstalls all dependencies every time this job runs
#In a lint job, in a Load & cache dependencies -> we can see npm ci command (Install Dependencies), it does not use caching
#But, for other jobs  such as test and build jobs, it uses caching - it gets the data from the cache
#It restores cache successfully and it did not run the command to install dependencies!
#This custom input works as intended